#!/bin/zsh

path+=("$HOME/.local/bin")
path+=("$HOME/.local/share/go/bin")

export EDITOR="nvim"

export FZF_DEFAULT_COMMAND='rg --files'
export FZF_DEFAULT_OPTS="--layout=reverse --cycle --border=double"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"

source "/home/levin/.local/share/cargo/env"
